[package]
name = "symbolique"
version = "0.1.0"
edition = "2021"

[dependencies]
lasso = { version = "0.7.2", features = ["multi-threaded"] }
rustc-hash = "1.1.0"
symbolique-proc = { version = "0.1.0", path = "../symbolique-proc" }
