[package]
name = "symbolique-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
fastrand = "2.0.1"
litrs = { version = "0.4.1", default-features = false }
sha2 = "0.10.8"
